"""initial schema

Revision ID: c9e19ac30e4e
Revises:
Create Date: 2026-08-16 02:26:11.017199
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c9e19ac30e4e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "games",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("selected_category", sa.String(length=32), nullable=True),
        sa.Column("requested_date", sa.Date(), nullable=True),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("total_rounds", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_games_expires_at"), "games", ["expires_at"], unique=False)
    op.create_index(op.f("ix_games_mode"), "games", ["mode"], unique=False)
    op.create_table(
        "prompts",
        sa.Column("id", sa.String(length=80), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("text", sa.String(length=160), nullable=False),
        sa.Column("fallback_answers", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_prompts_category"), "prompts", ["category"], unique=False)
    op.create_table(
        "puzzles",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("prompt_id", sa.String(length=80), nullable=False),
        sa.Column("puzzle_date", sa.Date(), nullable=True),
        sa.Column("answers", sa.JSON(), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["prompt_id"], ["prompts.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_puzzles_daily_date",
        "puzzles",
        ["puzzle_date"],
        unique=True,
        sqlite_where=sa.text("puzzle_date IS NOT NULL"),
    )
    op.create_index(
        "idx_puzzles_prompt_captured", "puzzles", ["prompt_id", "captured_at"], unique=False
    )
    op.create_table(
        "game_rounds",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("game_id", sa.String(length=36), nullable=False),
        sa.Column("round_number", sa.Integer(), nullable=False),
        sa.Column("puzzle_id", sa.String(length=36), nullable=False),
        sa.Column("found_ranks", sa.JSON(), nullable=False),
        sa.Column("guesses", sa.JSON(), nullable=False),
        sa.Column("misses", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["games.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["puzzle_id"], ["puzzles.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("game_id", "round_number", name="uq_game_round"),
    )
    op.create_index(op.f("ix_game_rounds_game_id"), "game_rounds", ["game_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_game_rounds_game_id"), table_name="game_rounds")
    op.drop_table("game_rounds")
    op.drop_index("idx_puzzles_prompt_captured", table_name="puzzles")
    op.drop_index(
        "idx_puzzles_daily_date",
        table_name="puzzles",
        sqlite_where=sa.text("puzzle_date IS NOT NULL"),
    )
    op.drop_table("puzzles")
    op.drop_index(op.f("ix_prompts_category"), table_name="prompts")
    op.drop_table("prompts")
    op.drop_index(op.f("ix_games_mode"), table_name="games")
    op.drop_index(op.f("ix_games_expires_at"), table_name="games")
    op.drop_table("games")
    # ### end Alembic commands ###
