/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Categories */
    get: operations["list_categories_api_v1_categories_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/daily/archive": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Archive */
    get: operations["list_archive_api_v1_daily_archive_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/daily/current": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["current_daily_api_v1_daily_current_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/games": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Game */
    post: operations["create_game_api_v1_games_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/games/{game_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Game */
    get: operations["get_game_api_v1_games__game_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/games/{game_id}/guesses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit Guess */
    post: operations["submit_guess_api_v1_games__game_id__guesses_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/games/{game_id}/give-up": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Give Up */
    post: operations["give_up_api_v1_games__game_id__give_up_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/games/{game_id}/next-round": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Next Round */
    post: operations["next_round_api_v1_games__game_id__next_round_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AnswerSlot */
    AnswerSlot: {
      /** Rank */
      rank: number;
      /** Points */
      points: number;
      status: components["schemas"]["SlotStatus"];
      /** Completion */
      completion?: string | null;
    };
    /** ArchivePuzzleOut */
    ArchivePuzzleOut: {
      /**
       * Date
       * Format: date
       */
      date: string;
      /** Number */
      number: number;
      category: components["schemas"]["CategoryOut"];
      /** Prompt */
      prompt: string;
    };
    /** DailyCurrentOut */
    DailyCurrentOut: {
      /** Date */
      date: string;
      /** Number */
      number: number;
      /** Timezone */
      timezone: string;
    };
    /** CategoryOut */
    CategoryOut: {
      /** Slug */
      slug: string;
      /** Name */
      name: string;
    };
    /** CreateGameRequest */
    CreateGameRequest: {
      mode: components["schemas"]["GameMode"];
      /** Date */
      date?: string | null;
      /** Category */
      category?: string | null;
      /** Recent Puzzle Ids */
      recent_puzzle_ids?: string[];
    };
    /**
     * GameMode
     * @enum {string}
     */
    GameMode: "daily" | "archive" | "random";
    /** GameState */
    GameState: {
      /** Id */
      id: string;
      mode: components["schemas"]["GameMode"];
      /** Puzzle Date */
      puzzle_date: string | null;
      /** Puzzle Number */
      puzzle_number: number | null;
      /** Round Number */
      round_number: number;
      /** Total Rounds */
      total_rounds: number;
      category: components["schemas"]["CategoryOut"];
      /** Prompt */
      prompt: string;
      /** Content Id */
      content_id?: string;
      /** Content Version */
      content_version?: string;
      /** Snapshot Source */
      snapshot_source?: string;
      /** Captured At */
      captured_at?: string | null;
      /** Score */
      score: number;
      /** Round Score */
      round_score: number;
      /** Misses */
      misses: number;
      /** Misses Remaining */
      misses_remaining: number;
      status: components["schemas"]["GameStatus"];
      /** Slots */
      slots: components["schemas"]["AnswerSlot"][];
      /** Round Summaries */
      round_summaries?: components["schemas"]["RoundSummary"][];
      last_result?: components["schemas"]["GuessResult"] | null;
    };
    /**
     * GameStatus
     * @enum {string}
     */
    GameStatus: "playing" | "round_complete" | "complete";
    /** GuessOutcome */
    GuessOutcome: "correct" | "incorrect" | "duplicate" | "too_broad" | "gave_up";
    /** MatchKind */
    MatchKind: "exact" | "alias" | "concept";
    /** GuessRequest */
    GuessRequest: {
      /** Guess */
      guess: string;
    };
    /** GuessResult */
    GuessResult: {
      /** Outcome */
      outcome: components["schemas"]["GuessOutcome"];
      /** Matched Ranks */
      matched_ranks: number[];
      /** Matched Rank */
      matched_rank?: number | null;
      /** Points Awarded */
      points_awarded: number;
      /** Combo Count */
      combo_count: number;
      /** Match Kind */
      match_kind?: components["schemas"]["MatchKind"] | null;
      /** Message */
      message: string;
    };
    /** RoundSummary */
    RoundSummary: {
      round_number: number;
      category: components["schemas"]["CategoryOut"];
      found: number;
      score: number;
      misses: number;
      puzzle_number?: number | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * SlotStatus
     * @enum {string}
     */
    SlotStatus: "hidden" | "found" | "revealed";
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  list_categories_api_v1_categories_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CategoryOut"][];
        };
      };
    };
  };
  list_archive_api_v1_daily_archive_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArchivePuzzleOut"][];
        };
      };
    };
  };
  current_daily_api_v1_daily_current_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DailyCurrentOut"];
        };
      };
    };
  };
  create_game_api_v1_games_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateGameRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GameState"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_game_api_v1_games__game_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GameState"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  submit_guess_api_v1_games__game_id__guesses_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GuessRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GameState"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  give_up_api_v1_games__game_id__give_up_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GameState"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  next_round_api_v1_games__game_id__next_round_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        game_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GameState"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
