"""Replace generated v3 endings with reviewed, natural Spanish adaptations."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "content" / "boards-v3.json"


def bank(*items: str) -> list[str]:
    if len(items) != 10:
        raise ValueError("Every board needs exactly ten completions")
    return list(items)


PACK: dict[str, tuple[list[str], list[list[str]]]] = {
    "cultura": (
        [
            "lo más español es",
            "algo muy español es",
            "ser español es",
            "antes de internet la gente",
            "sin móvil la gente",
            "cuando no había wifi la gente",
            "si piensas en España aparece",
            "España parece",
            "lo que recuerdo de España es",
            "en España se",
            "en los bares se",
            "cuando sales a cenar se",
            "antes la gente",
            "sin móvil la gente",
            "cuando no había notificaciones la gente",
            "mi primer móvil servía para",
            "un teléfono fijo servía para",
            "antes quedábamos para",
            "en España se",
            "en los bares se",
            "cuando sales a cenar se",
            "en una sobremesa se",
            "en una comida familiar se",
            "cuando visitas a la abuela se",
            "en las fiestas de mi pueblo se",
            "en una boda española se",
            "en Navidad se",
            "para vivir en España hay que",
            "viajar por España implica",
            "un día en España empieza por",
        ],
        [
            bank(
                "llegar tarde y decir «ya estoy»",
                "tener un bar favorito",
                "comer con pan",
                "discutir por fútbol",
                "convertir todo en sobremesa",
                "saludar con dos besos",
                "pedir una caña y quedarse tres horas",
                "decir «cinco minutos» y tardar media hora",
                "opinar aunque nadie haya preguntado",
                "celebrar cualquier cosa con comida",
            ),
            bank(
                "guardaba una silla en la playa",
                "llevaba tortilla en un táper",
                "ponía una terraza en cualquier acera",
                "llamaba a todo el mundo «jefe»",
                "conocía la carta del bar de memoria",
                "tenía una discusión familiar por el aire acondicionado",
                "aplaudía cuando aterrizaba el avión",
                "hacía amigos en la cola del supermercado",
                "decía que el pueblo era tranquilo y ponía música alta",
                "preguntaba cuándo te casabas",
            ),
            bank(
                "sol y playa, pero también montañas",
                "una mezcla de acentos",
                "un buen sitio para comer",
                "una fiesta que nunca termina",
                "más historia de la que cabe en un museo",
                "un poco de caos",
                "gente que sale tarde a cenar",
                "pueblos donde todos se conocen",
                "una sobremesa enorme",
                "una escapada para cada fin de semana",
            ),
            bank(
                "come tarde",
                "pide pan para mojar la salsa",
                "hace tiempo para el café",
                "se queda en la terraza",
                "brinda por cualquier motivo",
                "habla de fútbol",
                "sale a tomar algo después del trabajo",
                "pone una tapa en el centro",
                "discute y luego pide postre",
                "dice que solo será una rápida",
            ),
            bank(
                "tenía menos notificaciones",
                "leía el periódico en papel",
                "quedaba sin mandar ubicación",
                "usaba un mapa que se doblaba mal",
                "esperaba una semana para ver el capítulo",
                "no podía buscarlo todo al instante",
                "se aburría y salía a la calle",
                "tenía una agenda de papel",
                "escuchaba un disco entero",
                "preguntaba a alguien en vez de mirar el móvil",
            ),
            bank(
                "llamar a casa",
                "mandar mensajes de texto",
                "hacer fotos borrosas",
                "jugar a la serpiente",
                "guardar números de memoria",
                "escuchar un tono polifónico",
                "consultar la hora",
                "quedar con amigos",
                "presumir de tener cámara",
                "perderse buscando una dirección",
            ),
            bank(
                "come tarde",
                "pide pan para mojar la salsa",
                "hace tiempo para el café",
                "se queda en la terraza",
                "brinda por cualquier motivo",
                "habla de fútbol",
                "sale a tomar algo después del trabajo",
                "pone una tapa en el centro",
                "discute y luego pide postre",
                "dice que solo será una rápida",
            ),
            bank(
                "habla de todo menos de irse",
                "aparece alguien con otro postre",
                "repite la misma historia",
                "nadie mira el reloj",
                "arregla el mundo",
                "alguien pregunta por la boda",
                "sirve café aunque sea medianoche",
                "acaba hablando de la familia",
                "uno dice «la última» tres veces",
                "enfría la comida",
            ),
            bank(
                "baila aunque nadie sepa",
                "canta una canción de hace veinte años",
                "brinda con lo que haya",
                "come en una mesa enorme",
                "saluda a todo el pueblo",
                "ríe hasta tarde",
                "aplaude al recién llegado",
                "pregunta cuándo termina",
                "cena a una hora imposible",
                "improvisa un baile",
            ),
            bank(
                "levantarse con un café",
                "aprender a vivir con ruido",
                "encontrar una terraza para cada estado de ánimo",
                "tener un plan improvisado cada semana",
                "comer bien incluso con poco tiempo",
                "conocer a alguien en el ascensor",
                "hacer una escapada sin salir del país",
                "vivir entre fiestas y días festivos",
                "discutir por la temperatura del aire",
                "decir que te vas y quedarte un rato más",
            ),
        ],
    ),
    "personas": (
        [
            "mi pareja no sabe que",
            "mi ex confiesa que",
            "mi crush admite que",
            "mi ex",
            "mi crush",
            "la persona que me gusta",
            "cómo saber si alguien",
            "cuando te gusta alguien",
            "mi pareja",
            "la persona que me gusta",
            "mi crush",
            "alguien que te gusta",
            "en una primera cita",
            "en una cita",
            "cuando conoces a alguien",
            "cuando te gusta alguien",
            "cómo saber si alguien",
            "mi pareja",
            "cómo saber si alguien",
            "cuando conoces a alguien",
            "mi pareja",
            "cuando alguien te deja",
            "después de una ruptura",
            "cuando termina una relación",
            "no le escribas a tu ex si",
            "no mandes ese mensaje si",
            "no llames a tu ex cuando",
            "mi mejor amigo siempre",
            "mi vecino",
            "mi compañero de piso",
        ],
        [
            bank(
                "me he comido sus patatas",
                "guardo snacks de emergencia",
                "canto cuando estoy solo",
                "he visto su serie sin esperar",
                "sigo mirando su antiguo piso",
                "me sé su contraseña del wifi",
                "compré algo que no necesitaba",
                "he fingido entender la película",
                "necesito una siesta",
                "llevo tres días diciendo «luego lo hago»",
            ),
            bank(
                "mira mis stories",
                "me bloquea y desbloquea",
                "sigue teniendo mi sudadera",
                "ha cambiado de peluquería",
                "habla de mí con su grupo",
                "aparece en mis sugerencias",
                "conserva nuestras fotos",
                "se acuerda de mi cumpleaños",
                "vive demasiado cerca",
                "dice que está fenomenal",
            ),
            bank(
                "ha leído el mensaje tres veces",
                "se ríe de mis chistes malos",
                "pregunta por mi ex",
                "responde con un emoji",
                "sabe cuándo miento",
                "guarda capturas de pantalla",
                "se pone nervioso al saludar",
                "me manda memes a medianoche",
                "recuerda detalles absurdos",
                "dice que solo quiere amistad",
            ),
            bank(
                "te saluda aunque tenga prisa",
                "te mira y aparta la vista",
                "te pregunta por tu mascota",
                "se ríe de todo lo que dices",
                "se sabe tu café de memoria",
                "busca excusas para coincidir",
                "te contesta al segundo día",
                "te invita a una boda",
                "te habla de su ex",
                "te llama por tu nombre completo",
            ),
            bank(
                "hablar del ex sin querer",
                "pedir la cuenta demasiado pronto",
                "descubrir que ambos odian el cilantro",
                "decir que no tienes hambre y pedir postre",
                "reírse en el momento equivocado",
                "mirar el móvil debajo de la mesa",
                "llevar una camiseta demasiado cómoda",
                "hacer planes para la tercera cita",
                "preguntar por el signo del zodiaco",
                "decir «llego en cinco» desde casa",
            ),
            bank(
                "guarda una conversación para releerla",
                "se aprende tus horarios",
                "te recomienda una canción",
                "tarda una hora en elegir emoji",
                "te manda un meme que explica demasiado",
                "sonríe cuando apareces en línea",
                "se pone celoso de una serie",
                "pregunta si has llegado bien",
                "te cuenta un secreto innecesario",
                "dice que no quiere llamar la atención",
            ),
            bank(
                "te conoce demasiado",
                "te escucha de verdad",
                "te deja en visto con cariño",
                "miente sobre dónde está",
                "pide comida para compartir",
                "guarda capturas",
                "vive al lado",
                "se ríe de todo",
                "llega tarde a propósito",
                "ha vuelto con su ex",
            ),
            bank(
                "borras fotos y luego las restauras",
                "escuchas canciones tristes",
                "te haces amigo de su perro",
                "cambias de ruta para no coincidir",
                "dices que estás bien demasiado rápido",
                "miras si está en línea",
                "devuelves una sudadera seis meses tarde",
                "te apuntas al gimnasio el lunes",
                "silencias sus historias",
                "pides consejo a alguien que tampoco sabe",
            ),
            bank(
                "es después de medianoche",
                "has bebido dos copas",
                "quieres demostrar que has cambiado",
                "su cumpleaños es mañana",
                "lo has escrito y borrado cinco veces",
                "te acuerdas de una broma privada",
                "estás aburrido en el sofá",
                "su perro te cae mejor que él",
                "sabes que no responderá",
                "tienes el mensaje preparado desde ayer",
            ),
            bank(
                "te cubre cuando llegas tarde",
                "sabe dónde están tus llaves",
                "te recuerda que has quedado",
                "se ríe antes de que acabes la historia",
                "te manda comida cuando estás enfermo",
                "conoce tu peor foto",
                "te dice la verdad sin suavizarla",
                "te guarda sitio",
                "aparece con café",
                "te convence de salir de casa",
            ),
        ],
    ),
    "nombres": (
        [
            "María",
            "José",
            "Antonio",
            "Carmen",
            "Lucía",
            "Manuel",
            "Laura",
            "Javier",
            "Ana",
            "David",
            "Sofía",
            "Daniel",
            "Marta",
            "Pablo",
            "Elena",
            "Carlos",
            "Paula",
            "Miguel",
            "Alba",
            "Alejandro",
            "Sara",
            "Diego",
            "Isabel",
            "Fernando",
            "Aitana",
            "Rosalía",
            "Penélope",
            "Pedro",
            "Inés",
            "Lola",
        ],
        [
            bank(
                "García",
                "López",
                "Martínez",
                "Sánchez",
                "González",
                "Fernández",
                "Rodríguez",
                "Pérez",
                "Gómez",
                "Díaz",
            )
            for _ in range(30)
        ],
    ),
    "preguntas": (
        [
            "debería vender",
            "debería comprar",
            "me compensa vender",
            "debería escribirle a",
            "no le escribas a",
            "¿le escribo a",
            "puedo vivir sin",
            "es posible vivir sin",
            "cómo vivir sin",
            "es normal que",
            "por qué es normal que",
            "me preocupa que",
            "por qué mi perro",
            "por qué mi gato",
            "por qué mi conejo",
            "qué hacer si",
            "qué hago si",
            "y si",
            "me puedo comer",
            "puedo probar",
            "es seguro comer",
            "debería comprar",
            "qué debería comprar",
            "merece la pena comprar",
            "cómo saber si",
            "quiero saber si",
            "cómo comprobar si",
            "puedo dormir con",
            "es raro dormir con",
            "quién puede dormir con",
        ],
        [
            bank(
                "el coche",
                "mi casa",
                "mi móvil",
                "mi colección de cromos",
                "mi sofá",
                "mi consola",
                "mi bici",
                "mi cafetera",
                "mi guitarra",
                "mi vieja chaqueta",
            ),
            bank(
                "mi ex",
                "mi jefe",
                "mi crush",
                "mi madre",
                "el grupo del trabajo",
                "el vecino",
                "la persona que me dejó en visto",
                "mi médico",
                "mi casero",
                "nadie",
            ),
            bank(
                "café",
                "móvil",
                "internet",
                "pan",
                "música",
                "una siesta",
                "aire acondicionado",
                "mi serie favorita",
                "patatas",
                "quejarme",
            ),
            bank(
                "mi perro me mire así",
                "el móvil se caliente",
                "la nevera huela raro",
                "me cueste madrugar",
                "hable solo",
                "mi gato me ignore",
                "no quiera salir",
                "me ría en los nervios",
                "mi jefe escriba tarde",
                "necesite vacaciones",
            ),
            bank(
                "me sigue al baño",
                "no duerme",
                "ladra a la pared",
                "se esconde",
                "mira la lavadora",
                "tira el cuenco",
                "come hierba",
                "tiembla con la aspiradora",
                "se queda mirando",
                "huele las llaves",
            ),
            bank(
                "llegas tarde a una cita",
                "rompes algo prestado",
                "te quedas sin batería",
                "te escribe tu ex",
                "un vecino hace ruido",
                "tu perro come un calcetín",
                "se quema la cena",
                "pierdes las llaves",
                "no entiendes un contrato",
                "te da vergüenza preguntar",
            ),
            bank(
                "la piel de la fruta",
                "un hueso de aceituna",
                "comida de ayer",
                "un bocadillo enorme",
                "una flor",
                "hielo con limón",
                "la masa cruda",
                "un caramelo pegajoso",
                "la corteza del queso",
                "una guindilla",
            ),
            bank(
                "una planta",
                "un reloj",
                "un curso online",
                "una silla cómoda",
                "un altavoz",
                "una cámara instantánea",
                "una sartén nueva",
                "un billete de tren",
                "una lámpara",
                "un robot aspirador",
            ),
            bank(
                "te está mintiendo",
                "te escucha de verdad",
                "tu gato está enfadado",
                "el wifi funciona",
                "necesitas dormir",
                "le gustas a alguien",
                "una oferta es de verdad",
                "tu vecino te oye",
                "has dejado el horno encendido",
                "un mensaje era para ti",
            ),
            bank(
                "mi perro",
                "mi pareja",
                "un peluche",
                "la pared",
                "un colchón hinchable",
                "mi gato",
                "un sofá",
                "un desconocido",
                "mi compañero de piso",
                "una almohada",
            ),
        ],
    ),
    "animales": (
        [
            "mi perro se ha comido",
            "mi gato se ha comido",
            "mi conejo se ha comido",
            "mi perro no deja de",
            "mi gato no deja de",
            "mi conejo no deja de",
            "mi gato duerme",
            "mi perro duerme",
            "mi conejo duerme",
            "mi gato me",
            "mi perro me",
            "mi conejo me",
            "por qué mi perro",
            "por qué mi gato",
            "por qué mi conejo",
            "cuando mi perro",
            "cuando mi gato",
            "cuando mi conejo",
            "el perro del vecino",
            "el gato del vecino",
            "la mascota de mi hermana",
            "mi mascota sabe",
            "mi perro sabe",
            "mi gato sabe",
            "cómo saber si mi gato",
            "cómo saber si mi perro",
            "cómo saber si mi conejo",
            "animales que",
            "animales que pueden",
            "animales capaces de",
        ],
        [
            bank(
                "los deberes",
                "un calcetín",
                "el mando de la tele",
                "una planta",
                "una zapatilla",
                "la esponja",
                "una pelota",
                "un pañuelo",
                "el papel higiénico",
                "mi bocadillo",
            ),
            bank(
                "ladrar a la nada",
                "perseguirse la cola",
                "lamerme la mano",
                "mirar la pared",
                "pedir comida",
                "traer palos",
                "rascar la puerta",
                "dormir encima de mí",
                "morder su manta",
                "seguir su sombra",
            ),
            bank(
                "encima del teclado",
                "en mi cama",
                "dentro de una caja",
                "sobre mi ropa limpia",
                "al sol",
                "en el fregadero",
                "junto a la calefacción",
                "en la mochila",
                "en el felpudo",
                "donde no cabe",
            ),
            bank(
                "trae regalos",
                "ignora",
                "despierta a las seis",
                "persigue los cordones",
                "mira como si pagara el alquiler",
                "tira las cosas",
                "se esconde cuando llega gente",
                "se frota contra todo",
                "pide abrir la puerta",
                "se sienta sobre el portátil",
            ),
            bank(
                "come hierba",
                "inclina la cabeza",
                "ladra al espejo",
                "duerme tanto",
                "persigue su cola",
                "mira la lavadora",
                "tiembla con la aspiradora",
                "esconde los juguetes",
                "huye del baño",
                "sabe cuándo llego",
            ),
            bank(
                "me mira fijamente",
                "se emociona con la correa",
                "oye una bolsa",
                "me sigue al baño",
                "se queda dormido",
                "huele una bolsa",
                "trae un palo enorme",
                "se enfada con la lluvia",
                "se esconde bajo la mesa",
                "decide que es la hora de cenar",
            ),
            bank(
                "ladra a las tres",
                "se escapa por el portal",
                "conoce todos los ascensores",
                "persigue bicicletas",
                "se sienta en mi felpudo",
                "me reconoce desde lejos",
                "ladra cuando aparco",
                "se hace amigo de cualquiera",
                "trae calcetines",
                "sabe cuándo llueve",
            ),
            bank(
                "abrir una puerta",
                "reconocer mi voz",
                "encontrar comida",
                "recordar una ruta",
                "pedir agua",
                "encender una luz",
                "esconder un juguete",
                "avisar de una visita",
                "dormir con música",
                "elegir su sitio favorito",
            ),
            bank(
                "está contento",
                "quiere estar solo",
                "tiene hambre",
                "te ha perdonado",
                "ha visto algo",
                "quiere jugar",
                "está enfermo",
                "te reconoce",
                "está enfadado",
                "sabe que vas al veterinario",
            ),
            bank(
                "muerden cables",
                "se esconden en cajas",
                "corren de madrugada",
                "comen heno",
                "tiran el cuenco",
                "saltan al oír una bolsa",
                "se quedan quietos de repente",
                "roban servilletas",
                "duermen de lado",
                "miran desde la esquina",
            ),
        ],
    ),
    "entretenimiento": (
        [
            "la película en la que el protagonista",
            "la película donde el protagonista",
            "la historia en la que el protagonista",
            "la película donde sale",
            "la película que incluye",
            "una película con",
            "una serie sobre",
            "series sobre",
            "una serie acerca de",
            "la canción que dice",
            "la letra que repite",
            "una canción que habla de",
            "canciones para",
            "música para",
            "una canción para",
            "el cantante que",
            "la cantante que",
            "un cantante que",
            "series sobre",
            "una serie donde",
            "la mejor serie para",
            "la serie que todo el mundo",
            "esa serie que todo el mundo",
            "una serie que todo el mundo",
            "el capítulo que me hizo",
            "una serie que me hizo",
            "la serie que consiguió hacerme",
            "el personaje que",
            "el personaje de la serie que",
            "ese personaje que",
        ],
        [
            bank(
                "pierde la memoria",
                "viaja en el tiempo",
                "despierta en otro cuerpo",
                "se enamora del villano",
                "habla con fantasmas",
                "no sabe que está muerto",
                "recibe una llamada del futuro",
                "vive el mismo día",
                "adopta un perro",
                "se convierte en detective",
            ),
            bank(
                "un perro que roba la película",
                "un robot con sentimientos",
                "una actriz que nadie reconoce",
                "un pueblo demasiado tranquilo",
                "un mapa secreto",
                "un vecino sospechoso",
                "un villano con buen gusto",
                "un giro imposible",
                "una casa que respira",
                "una canción pegadiza",
            ),
            bank(
                "vecinos que se odian",
                "una familia con un secreto",
                "un detective torpe",
                "amistades imposibles",
                "viajes en el tiempo",
                "un restaurante en crisis",
                "un pueblo pequeño",
                "un grupo de amigos",
                "fantasmas con problemas",
                "una oficina caótica",
            ),
            bank(
                "na na na",
                "mi primer amor",
                "volver a casa",
                "bailar solo",
                "un verano entero",
                "no tiene sentido",
                "se me olvidó la letra",
                "todo ocurre al revés",
                "un silbido",
                "una frase pegadiza",
            ),
            bank(
                "dormir",
                "cantar en la ducha",
                "un viaje largo",
                "una boda",
                "hacer ejercicio",
                "llorar en silencio",
                "cocinar",
                "una fiesta",
                "un domingo raro",
                "pedir perdón",
            ),
            bank(
                "habla de volver",
                "suena en todas partes",
                "me hace reír",
                "canta con voz rota",
                "lleva un sombrero",
                "es imposible de encontrar",
                "tiene un silbido",
                "sale en una serie",
                "se parece a mi ex",
                "nadie sabe su nombre",
            ),
            bank(
                "vecinos que se odian",
                "una familia con un secreto",
                "un detective torpe",
                "amistades imposibles",
                "viajes en el tiempo",
                "un restaurante en crisis",
                "un pueblo pequeño",
                "un grupo de amigos",
                "fantasmas con problemas",
                "una oficina caótica",
            ),
            bank(
                "recomienda",
                "ha visto",
                "cita",
                "está viendo",
                "abandona",
                "conoce",
                "comenta",
                "odia",
                "termina",
                "finge no ver",
            ),
            bank(
                "llorar en el sofá",
                "reírme solo",
                "llamar a alguien después",
                "tener miedo a la oscuridad",
                "querer viajar",
                "recordar mi infancia",
                "cantar los créditos",
                "mirar detrás de la cortina",
                "pensar en mi ex",
                "pedir palomitas",
            ),
            bank(
                "se roba la serie",
                "siempre llega tarde",
                "nadie entiende",
                "tiene la mejor frase",
                "guarda un secreto",
                "miente fatal",
                "desaparece en el capítulo tres",
                "lleva un abrigo increíble",
                "salva el día por accidente",
                "se queda con el perro",
            ),
        ],
    ),
    "comida": (
        [
            "me he comido por accidente",
            "me he tragado por accidente",
            "he comido sin querer",
            "mi perro se ha comido",
            "mi gato se ha comido",
            "mi mascota se ha comido",
            "he bebido demasiado",
            "he tomado demasiado",
            "después de beber",
            "me sabe la boca a",
            "todo me sabe a",
            "la cocina huele a",
            "nunca mezcles",
            "no mezcles",
            "qué pasa si mezclas",
            "cuando comes demasiado",
            "si comes demasiado",
            "después de comer demasiado",
            "la comida que más",
            "lo que más me gusta comer",
            "mi comida favorita",
            "qué hacer si te tragas",
            "qué pasa si te tragas",
            "si te tragas",
            "he encontrado",
            "en la nevera he encontrado",
            "qué hago con lo que he encontrado",
            "mi nevera huele a",
            "la cocina huele a",
            "la bolsa huele a",
        ],
        [
            bank(
                "una semilla",
                "un hueso de aceituna",
                "un trozo de papel",
                "la piel de una mandarina",
                "un pelo",
                "una espina",
                "un caramelo",
                "una miga enorme",
                "una moneda de chocolate",
                "mi propio bocadillo",
            ),
            bank(
                "un calcetín",
                "una pelota",
                "el mando de la tele",
                "una planta",
                "un pañuelo",
                "una esponja",
                "un juguete",
                "la comida del gato",
                "un guante",
                "mi bocadillo",
            ),
            bank(
                "café",
                "bebida energética",
                "refresco con hielo",
                "horchata",
                "agua después de correr",
                "batido",
                "té",
                "limonada",
                "caldo",
                "mi propia paciencia",
            ),
            bank(
                "tupper olvidado",
                "ajo",
                "palomitas",
                "salsa picante",
                "cebolla",
                "café frío",
                "nevera cerrada",
                "queso fuerte",
                "pan tostado",
                "domingo por la tarde",
            ),
            bank(
                "café y una bebida energética",
                "salsa picante y chocolate",
                "sandía y sal",
                "pasta y azúcar",
                "queso azul y mermelada",
                "atún y canela",
                "patatas y helado",
                "zumo y leche",
                "pepino y chocolate",
                "todo lo que encuentres",
            ),
            bank(
                "te entra sueño",
                "pides postre igual",
                "prometes empezar el lunes",
                "te arrepientes en el sofá",
                "necesitas caminar",
                "culpas al pan",
                "te da sed",
                "te quedas sin sitio para el café",
                "miras recetas saludables",
                "dices que mañana cenas ligero",
            ),
            bank(
                "me recuerda a mi infancia",
                "se come con las manos",
                "cabe en un táper",
                "tiene queso",
                "se prepara en diez minutos",
                "lleva salsa",
                "aparece en una fiesta",
                "puedes compartir",
                "sabe mejor al día siguiente",
                "no necesita cubiertos",
            ),
            bank(
                "un hueso pequeño",
                "una espina",
                "un caramelo",
                "un cubito de hielo",
                "un pelo",
                "un trozo de plástico",
                "una semilla",
                "una miga",
                "un chicle",
                "una uña",
            ),
            bank(
                "un tupper de hace una semana",
                "una salsa misteriosa",
                "medio limón",
                "un yogur sin fecha",
                "una patata con raíces",
                "un queso que habla solo",
                "una bolsa de espinacas",
                "un táper sin dueño",
                "un huevo sospechoso",
                "un tesoro detrás de la leche",
            ),
            bank(
                "tupper olvidado",
                "cebolla frita",
                "queso curado",
                "ajo",
                "pescado del martes",
                "una salsa casera",
                "pan húmedo",
                "sobras",
                "la comida del vecino",
                "algo que debería haber tirado",
            ),
        ],
    ),
}


def main() -> None:
    payload = json.loads(CONTENT.read_text(encoding="utf-8"))
    for category, (prompts, banks) in PACK.items():
        boards = [board for board in payload["boards"] if board["category"] == category]
        expected_bank_count = 30 if category == "nombres" else 10
        if len(boards) != 30 or len(prompts) != 30 or len(banks) != expected_bank_count:
            raise ValueError(f"{category}: expected 30 prompts and 10 answer banks")
        for index, board in enumerate(boards):
            board["prompt"] = prompts[index]
            board["completions"] = banks[index if category == "nombres" else index // 3]
            board["review"].update(
                {
                    "guessable_count": 7,
                    "surprising_count": 2,
                    "distinct_ideas": 10,
                    "approval_status": "approved",
                }
            )
            board["source"]["inspiration"] = (
                "Original-style autocomplete game stem, localized for Spain"
            )
            board["source"]["localization_note"] = (
                "Adaptación española curada; no es una copia literal ni una "
                "respuesta en tiempo real."
            )
    CONTENT.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
